import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'], // Add the weights you need
});

export const metadata: Metadata = {
  title: "To Do List",
  description: "Generated by Salma",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
         className={poppins.className}
      >
        {children}
      </body>
    </html>
  );
}
